module.exports = [
    'Lagaan|2001|Bollywood|Drama, Sports|Ashutosh Gowariker|Aamir Khan;Gracy Singh;Rachel Shelley|8.1',
    'PK|2014|Bollywood|Comedy, Drama|Rajkumar Hirani|Aamir Khan;Anushka Sharma;Sushant Singh Rajput|8.1',
    'Queen|2013|Bollywood|Comedy, Drama|Vikas Bahl|Kangana Ranaut;Rajkummar Rao;Lisa Haydon|8.1',
    'Barfi!|2012|Bollywood|Comedy, Drama|Anurag Basu|Ranbir Kapoor;Priyanka Chopra;Ileana DCruz|8.1',
    'Kahaani|2012|Bollywood|Thriller, Mystery|Sujoy Ghosh|Vidya Balan;Parambrata Chattopadhyay;Nawazuddin Siddiqui|8.1',
    'Drishyam|2015|Bollywood|Crime, Thriller|Nishikant Kamat|Ajay Devgn;Tabu;Shriya Saran|8.2',
    'Drishyam 2|2022|Bollywood|Crime, Thriller|Abhishek Pathak|Ajay Devgn;Tabu;Akshaye Khanna|8.0',
    'Uri: The Surgical Strike|2019|Bollywood|Action, War|Aditya Dhar|Vicky Kaushal;Yami Gautam;Paresh Rawal|8.2',
    'War|2019|Bollywood|Action, Thriller|Siddharth Anand|Hrithik Roshan;Tiger Shroff;Vaani Kapoor|6.5',
    'Kabir Singh|2019|Bollywood|Romance, Drama|Sandeep Reddy Vanga|Shahid Kapoor;Kiara Advani;Arjan Bajwa|7.0',
    'Raazi|2018|Bollywood|Thriller, Drama|Meghna Gulzar|Alia Bhatt;Vicky Kaushal;Jaideep Ahlawat|7.7',
    'Talvar|2015|Bollywood|Crime, Drama|Meghna Gulzar|Irrfan Khan;Konkona Sen Sharma;Neeraj Kabi|8.1',
    'Haider|2014|Bollywood|Crime, Drama|Vishal Bhardwaj|Shahid Kapoor;Tabu;Kay Kay Menon|8.1',
    'Maqbool|2003|Bollywood|Crime, Drama|Vishal Bhardwaj|Irrfan Khan;Tabu;Pankaj Kapur|8.0',
    'Omkara|2006|Bollywood|Crime, Drama|Vishal Bhardwaj|Ajay Devgn;Kareena Kapoor;Saif Ali Khan|8.0',
    'Piku|2015|Bollywood|Comedy, Drama|Shoojit Sircar|Deepika Padukone;Amitabh Bachchan;Irrfan Khan|7.6',
    'October|2018|Bollywood|Drama, Romance|Shoojit Sircar|Varun Dhawan;Banita Sandhu;Gitanjali Rao|7.5',
    'Vicky Donor|2012|Bollywood|Comedy, Romance|Shoojit Sircar|Ayushmann Khurrana;Yami Gautam;Annu Kapoor|7.7',
    'Article 15|2019|Bollywood|Crime, Drama|Anubhav Sinha|Ayushmann Khurrana;Isha Talwar;Sayani Gupta|8.1',
    'Mulk|2018|Bollywood|Drama|Anubhav Sinha|Rishi Kapoor;Taapsee Pannu;Prateik Babbar|7.9',
    'Thappad|2020|Bollywood|Drama|Anubhav Sinha|Taapsee Pannu;Pavail Gulati;Dia Mirza|7.8',
    'Pink|2016|Bollywood|Drama, Thriller|Aniruddha Roy Chowdhury|Amitabh Bachchan;Taapsee Pannu;Kirti Kulhari|8.1',
    'Badhaai Ho|2018|Bollywood|Comedy, Drama|Amit Ravindernath Sharma|Ayushmann Khurrana;Sanya Malhotra;Neena Gupta|8.0',
    'Bala|2019|Bollywood|Comedy|Amar Kaushik|Ayushmann Khurrana;Bhumi Pednekar;Yami Gautam|7.3',
    'Dream Girl|2019|Bollywood|Comedy, Romance|Raaj Shaandilyaa|Ayushmann Khurrana;Nushrratt Bharuccha;Annu Kapoor|7.0',
    'Shubh Mangal Zyada Saavdhan|2020|Bollywood|Comedy, Romance|Hitesh Kewalya|Ayushmann Khurrana;Jitendra Kumar;Gajraj Rao|6.9',
    'Bareilly Ki Barfi|2017|Bollywood|Comedy, Romance|Ashwiny Iyer Tiwari|Ayushmann Khurrana;Kriti Sanon;Rajkummar Rao|7.5',
    'Nil Battey Sannata|2015|Bollywood|Drama|Ashwiny Iyer Tiwari|Swara Bhasker;Ratna Pathak Shah;Pankaj Tripathi|8.1',
    'Mimi|2021|Bollywood|Comedy, Drama|Laxman Utekar|Kriti Sanon;Pankaj Tripathi;Sai Tamhankar|7.8',
    'Luka Chuppi|2019|Bollywood|Comedy, Romance|Laxman Utekar|Kartik Aaryan;Kriti Sanon;Pankaj Tripathi|6.3',
    'Chhichhore|2019|Bollywood|Comedy, Drama|Nitesh Tiwari|Sushant Singh Rajput;Shraddha Kapoor;Varun Sharma|8.3',
    'Bawaal|2023|Bollywood|Drama, Romance|Nitesh Tiwari|Varun Dhawan;Janhvi Kapoor;Manoj Pahwa|6.7',
    'Mardaani|2014|Bollywood|Action, Thriller|Pradeep Sarkar|Rani Mukerji;Tahir Raj Bhasin;Jisshu Sengupta|7.3',
    'Mardaani 2|2019|Bollywood|Action, Thriller|Gopi Puthran|Rani Mukerji;Vishal Jethwa;Shruti Bapna|7.4',
    'Krrish|2006|Bollywood|Action, Sci-Fi|Rakesh Roshan|Hrithik Roshan;Priyanka Chopra;Rekha|6.4',
    'Koi... Mil Gaya|2003|Bollywood|Sci-Fi, Drama|Rakesh Roshan|Hrithik Roshan;Preity Zinta;Rekha|7.1',
    'Krrish 3|2013|Bollywood|Action, Sci-Fi|Rakesh Roshan|Hrithik Roshan;Priyanka Chopra;Vivek Oberoi|5.3',
    'Agneepath|2012|Bollywood|Action, Drama|Karan Malhotra|Hrithik Roshan;Sanjay Dutt;Priyanka Chopra|6.9',
    'Don|2006|Bollywood|Action, Thriller|Farhan Akhtar|Shah Rukh Khan;Priyanka Chopra;Arjun Rampal|7.1',
    'Don 2|2011|Bollywood|Action, Thriller|Farhan Akhtar|Shah Rukh Khan;Priyanka Chopra;Boman Irani|7.0',
    'Dil Chahta Hai|2001|Bollywood|Comedy, Drama|Farhan Akhtar|Aamir Khan;Saif Ali Khan;Akshaye Khanna|8.1',
    'Lakshya|2004|Bollywood|Drama, War|Farhan Akhtar|Hrithik Roshan;Preity Zinta;Amitabh Bachchan|7.8',
    'Luck By Chance|2009|Bollywood|Drama|Zoya Akhtar|Farhan Akhtar;Konkona Sen Sharma;Rishi Kapoor|7.1',
    'Dil Dhadakne Do|2015|Bollywood|Comedy, Drama|Zoya Akhtar|Anil Kapoor;Priyanka Chopra;Ranveer Singh|7.0',
    'Jab We Met|2007|Bollywood|Comedy, Romance|Imtiaz Ali|Shahid Kapoor;Kareena Kapoor;Tarun Arora|7.9',
    'Rockstar|2011|Bollywood|Drama, Music|Imtiaz Ali|Ranbir Kapoor;Nargis Fakhri;Shammi Kapoor|7.7',
    'Tamasha|2015|Bollywood|Drama, Romance|Imtiaz Ali|Ranbir Kapoor;Deepika Padukone;Piyush Mishra|7.3',
    'Highway|2014|Bollywood|Drama, Romance|Imtiaz Ali|Alia Bhatt;Randeep Hooda;Durgesh Kumar|7.6',
    'Love Aaj Kal|2009|Bollywood|Comedy, Romance|Imtiaz Ali|Saif Ali Khan;Deepika Padukone;Rishi Kapoor|6.8',
    'Rock On!!|2008|Bollywood|Drama, Music|Abhishek Kapoor|Farhan Akhtar;Arjun Rampal;Purab Kohli|7.7',
    'Kai Po Che!|2013|Bollywood|Drama, Sports|Abhishek Kapoor|Sushant Singh Rajput;Rajkummar Rao;Amit Sadh|7.8',
    'Kedarnath|2018|Bollywood|Drama, Romance|Abhishek Kapoor|Sushant Singh Rajput;Sara Ali Khan;Nitish Bharadwaj|6.6',
    'Udaan|2010|Bollywood|Drama|Vikramaditya Motwane|Rajat Barmecha;Ronit Roy;Aayan Boradia|8.1',
    'Lootera|2013|Bollywood|Drama, Romance|Vikramaditya Motwane|Ranveer Singh;Sonakshi Sinha;Barun Chanda|7.3',
    'Trapped|2016|Bollywood|Thriller, Drama|Vikramaditya Motwane|Rajkummar Rao;Geetanjali Thapa;Khushboo Upadhyay|7.5',
    'Bhavesh Joshi Superhero|2018|Bollywood|Action, Drama|Vikramaditya Motwane|Harshvardhan Kapoor;Priyanshu Painyuli;Nishikant Kamat|7.6',
    'Rang De Basanti|2006|Bollywood|Comedy, Drama|Rakeysh Omprakash Mehra|Aamir Khan;Siddharth;Soha Ali Khan|8.1',
    'Delhi-6|2009|Bollywood|Drama|Rakeysh Omprakash Mehra|Abhishek Bachchan;Sonam Kapoor;Waheeda Rehman|6.3',
    'Bhaag Milkha Bhaag|2013|Bollywood|Drama, Sports|Rakeysh Omprakash Mehra|Farhan Akhtar;Sonam Kapoor;Divya Dutta|8.2',
    'Raanjhanaa|2013|Bollywood|Drama, Romance|Aanand L. Rai|Dhanush;Sonam Kapoor;Abhay Deol|7.6',
    'Tanu Weds Manu Returns|2015|Bollywood|Comedy, Romance|Aanand L. Rai|Kangana Ranaut;R. Madhavan;Deepak Dobriyal|7.6',
    'Atrangi Re|2021|Bollywood|Drama, Romance|Aanand L. Rai|Dhanush;Sara Ali Khan;Akshay Kumar|6.5',
    'Newton|2017|Bollywood|Comedy, Drama|Amit V. Masurkar|Rajkummar Rao;Pankaj Tripathi;Anjali Patil|7.6',
    'Joram|2023|Bollywood|Thriller, Drama|Devashish Makhija|Manoj Bajpayee;Mohd. Zeeshan Ayyub;Smita Tambe|7.0',
    'Madgaon Express|2024|Bollywood|Comedy|Kunal Kemmu|Divyenndu;Pratik Gandhi;Avinash Tiwary|7.2',
    'Bhool Chuk Maaf|2024|Bollywood|Comedy, Drama|Karan Sharma|Rajkummar Rao;Wamiqa Gabbi;Seema Pahwa|6.8',
    '12th Fail|2023|Bollywood|Drama, Biography|Vidhu Vinod Chopra|Vikrant Massey;Medha Shankr;Anant Joshi|8.8',
    'Munna Bhai M.B.B.S.|2003|Bollywood|Comedy, Drama|Rajkumar Hirani|Sanjay Dutt;Arshad Warsi;Gracy Singh|8.1',
    'Lage Raho Munna Bhai|2006|Bollywood|Comedy, Drama|Rajkumar Hirani|Sanjay Dutt;Arshad Warsi;Vidya Balan|8.0',
    'Sanju|2018|Bollywood|Drama, Biography|Rajkumar Hirani|Ranbir Kapoor;Paresh Rawal;Vicky Kaushal|7.6',
    'Ghajini|2008|Bollywood|Action, Thriller|A.R. Murugadoss|Aamir Khan;Asin;Jiah Khan|7.3',
    'Sultan|2016|Bollywood|Drama, Sports|Ali Abbas Zafar|Salman Khan;Anushka Sharma;Randeep Hooda|7.1',
    'Tiger Zinda Hai|2017|Bollywood|Action, Thriller|Ali Abbas Zafar|Salman Khan;Katrina Kaif;Paresh Rawal|5.9',
    'Baahubali: The Beginning|2015|Tollywood|Action, Adventure|S. S. Rajamouli|Prabhas;Rana Daggubati;Anushka Shetty|8.0',
    'Baahubali 2: The Conclusion|2017|Tollywood|Action, Drama|S. S. Rajamouli|Prabhas;Rana Daggubati;Anushka Shetty|8.2',
    'RRR|2022|Tollywood|Action, Drama|S. S. Rajamouli|N. T. Rama Rao Jr.;Ram Charan;Alia Bhatt|7.8',
    'Magadheera|2009|Tollywood|Action, Fantasy|S. S. Rajamouli|Ram Charan;Kajal Aggarwal;Srihari|7.7',
    'Eega|2012|Tollywood|Fantasy, Action|S. S. Rajamouli|Nani;Sudeep;Samantha Ruth Prabhu|7.7',
    'Yamadonga|2007|Tollywood|Fantasy, Comedy|S. S. Rajamouli|N. T. Rama Rao Jr.;Priyamani;Mohan Babu|7.2',
    'Chatrapathi|2005|Tollywood|Action, Drama|S. S. Rajamouli|Prabhas;Shriya Saran;Bhanupriya|7.6',
    'Vikramarkudu|2006|Tollywood|Action, Comedy|S. S. Rajamouli|Ravi Teja;Anushka Shetty;Vineet Kumar|7.7',
    'Sye|2004|Tollywood|Action, Sports|S. S. Rajamouli|Nithiin;Genelia Dsouza;Shashank|7.1',
    'Pushpa: The Rise|2021|Tollywood|Action, Crime|Sukumar|Allu Arjun;Rashmika Mandanna;Fahadh Faasil|7.6',
    'Arya|2004|Tollywood|Romance, Comedy|Sukumar|Allu Arjun;Anu Mehta;Siva Balaji|7.8',
    'Arya 2|2009|Tollywood|Action, Comedy|Sukumar|Allu Arjun;Kajal Aggarwal;Navdeep|7.4',
    'Rangasthalam|2018|Tollywood|Action, Drama|Sukumar|Ram Charan;Samantha Ruth Prabhu;Aadhi Pinisetty|8.2',
    '1: Nenokkadine|2014|Tollywood|Action, Thriller|Sukumar|Mahesh Babu;Kriti Sanon;Nassar|8.0',
    'Arjun Reddy|2017|Tollywood|Drama, Romance|Sandeep Reddy Vanga|Vijay Deverakonda;Shalini Pandey;Rahul Ramakrishna|8.0',
    'Jersey|2019|Tollywood|Drama, Sports|Gowtam Tinnanuri|Nani;Shraddha Srinath;Satyaraj|8.5',
    'Malli Raava|2017|Tollywood|Drama, Romance|Gowtam Tinnanuri|Sumanth;Aakanksha Singh;Annapoorna|7.6',
    'Mahanati|2018|Tollywood|Drama, Biography|Nag Ashwin|Keerthy Suresh;Dulquer Salmaan;Samantha Ruth Prabhu|8.4',
    'Kalki 2898 AD|2024|Tollywood|Sci-Fi, Action|Nag Ashwin|Prabhas;Deepika Padukone;Amitabh Bachchan|7.3',
    'Yevade Subramanyam|2015|Tollywood|Adventure, Drama|Nag Ashwin|Nani;Vijay Deverakonda;Malavika Nair|7.6',
    'Ala Vaikunthapurramuloo|2020|Tollywood|Action, Comedy|Trivikram Srinivas|Allu Arjun;Pooja Hegde;Tabu|7.3',
    'Athadu|2005|Tollywood|Action, Thriller|Trivikram Srinivas|Mahesh Babu;Trisha Krishnan;Sonu Sood|8.2',
    'Khaleja|2010|Tollywood|Action, Fantasy|Trivikram Srinivas|Mahesh Babu;Anushka Shetty;Prakash Raj|7.6',
    'Julayi|2012|Tollywood|Action, Comedy|Trivikram Srinivas|Allu Arjun;Ileana DCruz;Rajendra Prasad|7.2',
    'S/O Satyamurthy|2015|Tollywood|Drama, Action|Trivikram Srinivas|Allu Arjun;Upendra;Samantha Ruth Prabhu|7.1',
    'Aravinda Sametha Veera Raghava|2018|Tollywood|Action, Drama|Trivikram Srinivas|N. T. Rama Rao Jr.;Pooja Hegde;Jagapathi Babu|7.3',
    'Guntur Kaaram|2024|Tollywood|Action, Drama|Trivikram Srinivas|Mahesh Babu;Sreeleela;Meenakshi Chaudhary|5.6',
    'Pokiri|2006|Tollywood|Action, Crime|Puri Jagannadh|Mahesh Babu;Ileana DCruz;Prakash Raj|8.0',
    'Businessman|2012|Tollywood|Action, Crime|Puri Jagannadh|Mahesh Babu;Kajal Aggarwal;Prakash Raj|7.2',
    'Temper|2015|Tollywood|Action, Crime|Puri Jagannadh|N. T. Rama Rao Jr.;Kajal Aggarwal;Prakash Raj|7.4',
    'iSmart Shankar|2019|Tollywood|Action, Sci-Fi|Puri Jagannadh|Ram Pothineni;Nabha Natesh;Nidhhi Agerwal|5.7',
    'Double iSmart|2024|Tollywood|Action, Sci-Fi|Puri Jagannadh|Ram Pothineni;Sanjay Dutt;Kavya Thapar|5.4',
    'Bommarillu|2006|Tollywood|Comedy, Drama|Bhaskar|Siddharth;Genelia Dsouza;Prakash Raj|8.2',
    'Parugu|2008|Tollywood|Action, Romance|Bhaskar|Allu Arjun;Sheela Kaur;Prakash Raj|7.1',
    'Orange|2010|Tollywood|Drama, Romance|Bhaskar|Ram Charan;Genelia Dsouza;Shazahn Padamsee|6.6',
    'Oopiri|2016|Tollywood|Comedy, Drama|Vamsi Paidipally|Nagarjuna;Karthi;Tamannaah|8.0',
    'Maharshi|2019|Tollywood|Action, Drama|Vamsi Paidipally|Mahesh Babu;Pooja Hegde;Allari Naresh|7.2',
    'Brindavanam|2010|Tollywood|Comedy, Drama|Vamsi Paidipally|N. T. Rama Rao Jr.;Kajal Aggarwal;Samantha Ruth Prabhu|7.1',
    'Leader|2010|Tollywood|Drama|Sekhar Kammula|Rana Daggubati;Richa Gangopadhyay;Priya Anand|8.0',
    'Happy Days|2007|Tollywood|Comedy, Drama|Sekhar Kammula|Varun Sandesh;Tamannaah;Nikhil Siddharth|7.7',
    'Godavari|2006|Tollywood|Drama, Romance|Sekhar Kammula|Sumanth;Kamalinee Mukherjee;Neetu Chandra|8.3',
    'Fidaa|2017|Tollywood|Drama, Romance|Sekhar Kammula|Varun Tej;Sai Pallavi;Raja Chembolu|7.4',
    'Love Story|2021|Tollywood|Drama, Romance|Sekhar Kammula|Naga Chaitanya;Sai Pallavi;Easwari Rao|6.9',
    'Vedam|2010|Tollywood|Drama|Krish Jagarlamudi|Allu Arjun;Manchu Manoj;Anushka Shetty|8.1',
    'Kanche|2015|Tollywood|Drama, War|Krish Jagarlamudi|Varun Tej;Pragya Jaiswal;Nikitin Dheer|7.9',
    'Gautamiputra Satakarni|2017|Tollywood|Action, History|Krish Jagarlamudi|Nandamuri Balakrishna;Shriya Saran;Hema Malini|6.6',
    'Sye Raa Narasimha Reddy|2019|Tollywood|Action, History|Surender Reddy|Chiranjeevi;Nayanthara;Amitabh Bachchan|7.3',
    'Kick|2009|Tollywood|Action, Comedy|Surender Reddy|Ravi Teja;Ileana DCruz;Shaam|8.0',
    'Race Gurram|2014|Tollywood|Action, Comedy|Surender Reddy|Allu Arjun;Shruti Haasan;Shaam|7.3',
    'Agent|2023|Tollywood|Action, Thriller|Surender Reddy|Akhil Akkineni;Sakshi Vaidya;Mammootty|4.7',
    'Bimbisara|2022|Tollywood|Fantasy, Action|Mallidi Vassishta|Nandamuri Kalyan Ram;Catherine Tresa;Samyuktha|6.9',
    'Hanu-Man|2024|Tollywood|Fantasy, Action|Prasanth Varma|Teja Sajja;Amritha Aiyer;Varalaxmi Sarathkumar|7.8',
    'Zombie Reddy|2021|Tollywood|Comedy, Horror|Prasanth Varma|Teja Sajja;Anandi;Daksha Nagarkar|6.8',
    'Adhugo|2018|Tollywood|Comedy|Ravi Babu|Abhishek Varma;Nabha Natesh;Ravi Babu|5.4',
    'Pelli Choopulu|2016|Tollywood|Comedy, Romance|Tharun Bhascker|Vijay Deverakonda;Ritu Varma;Priyadarshi|8.2',
    'Ee Nagaraniki Emaindi|2018|Tollywood|Comedy, Drama|Tharun Bhascker|Vishwak Sen;Sai Sushanth Reddy;Abhinav Gomatam|7.8',
    'Keedaa Cola|2023|Tollywood|Crime, Comedy|Tharun Bhascker|Chaitanya Rao;Rag Mayur;Brahmanandam|7.0',
    'Brochevarevarura|2019|Tollywood|Comedy, Crime|Vivek Athreya|Sree Vishnu;Nivetha Thomas;Nivetha Pethuraj|8.0',
    'Mental Madhilo|2017|Tollywood|Comedy, Romance|Vivek Athreya|Sree Vishnu;Nivetha Pethuraj;Amrutha Srinivasan|7.5',
    'Ante Sundaraniki|2022|Tollywood|Comedy, Romance|Vivek Athreya|Nani;Nazriya Nazim;Naresh|7.6',
    'Saripodhaa Sanivaaram|2024|Tollywood|Action, Thriller|Vivek Athreya|Nani;S. J. Suryah;Priyanka Arul Mohan|7.1',
    'Dasara|2023|Tollywood|Action, Drama|Srikanth Odela|Nani;Keerthy Suresh;Dheekshith Shetty|6.8',
    'Hi Nanna|2023|Tollywood|Drama, Romance|Shouryuv|Nani;Mrunal Thakur;Kiara Khanna|8.1',
    'Majili|2019|Tollywood|Drama, Romance|Shiva Nirvana|Naga Chaitanya;Samantha Ruth Prabhu;Divyansha Kaushik|7.2',
    'Ninnu Kori|2017|Tollywood|Drama, Romance|Shiva Nirvana|Nani;Nivetha Thomas;Aadhi Pinisetty|7.4',
    'Geetha Govindam|2018|Tollywood|Comedy, Romance|Parasuram|Vijay Deverakonda;Rashmika Mandanna;Subbaraju|7.7',
    'Sarkaru Vaari Paata|2022|Tollywood|Action, Comedy|Parasuram|Mahesh Babu;Keerthy Suresh;Samuthirakani|5.6',
    'Lucky Baskhar|2024|Tollywood|Crime, Drama|Venky Atluri|Dulquer Salmaan;Meenakshi Chaudhary;Ayesha Khan|7.8',
    'Sir|2023|Tollywood|Drama|Venky Atluri|Dhanush;Samyuktha;Sai Kumar|7.3',
    'Tillu Square|2024|Tollywood|Comedy, Crime|Mallik Ram|Siddhu Jonnalagadda;Anupama Parameswaran;Muralidhar Goud|7.1',
    'DJ Tillu|2022|Tollywood|Comedy, Crime|Vimal Krishna|Siddhu Jonnalagadda;Neha Shetty;Prince Cecil|7.2',
    'Mathu Vadalara|2019|Tollywood|Comedy, Crime|Ritesh Rana|Sri Simha;Naresh Agastya;Athulya Chandra|7.8',
    'Mathu Vadalara 2|2024|Tollywood|Comedy, Crime|Ritesh Rana|Sri Simha;Satya;Faria Abdullah|7.0',
    'Salaar: Part 1 - Ceasefire|2023|Tollywood|Action, Thriller|Prashanth Neel|Prabhas;Prithviraj Sukumaran;Shruti Haasan|6.6',
    'Devara: Part 1|2024|Tollywood|Action, Drama|Koratala Siva|N. T. Rama Rao Jr.;Janhvi Kapoor;Saif Ali Khan|6.7',
    'Mirchi|2013|Tollywood|Action, Drama|Koratala Siva|Prabhas;Anushka Shetty;Richa Gangopadhyay|7.3',
    'Janatha Garage|2016|Tollywood|Action, Drama|Koratala Siva|N. T. Rama Rao Jr.;Mohanlal;Samantha Ruth Prabhu|7.2',
    'Bharat Ane Nenu|2018|Tollywood|Action, Drama|Koratala Siva|Mahesh Babu;Kiara Advani;Prakash Raj|7.5',
    'Acharya|2022|Tollywood|Action, Drama|Koratala Siva|Chiranjeevi;Ram Charan;Pooja Hegde|3.8',
    'Vikram|2022|South Indian|Action, Thriller|Lokesh Kanagaraj|Kamal Haasan;Fahadh Faasil;Vijay Sethupathi|8.3',
    'Kaithi|2019|South Indian|Action, Thriller|Lokesh Kanagaraj|Karthi;Narain;Arjun Das|8.5',
    'Master|2021|South Indian|Action, Thriller|Lokesh Kanagaraj|Vijay;Vijay Sethupathi;Malavika Mohanan|7.3',
    'Leo|2023|South Indian|Action, Thriller|Lokesh Kanagaraj|Vijay;Sanjay Dutt;Trisha Krishnan|7.2',
    'Maanagaram|2017|South Indian|Thriller|Lokesh Kanagaraj|Sundeep Kishan;Sri;Regina Cassandra|8.1',
    'Jailer|2023|South Indian|Action, Comedy|Nelson Dilipkumar|Rajinikanth;Vinayakan;Ramya Krishnan|7.0',
    'Beast|2022|South Indian|Action, Comedy|Nelson Dilipkumar|Vijay;Pooja Hegde;Selvaraghavan|5.2',
    'Doctor|2021|South Indian|Action, Comedy|Nelson Dilipkumar|Sivakarthikeyan;Priyanka Arul Mohan;Vinay Rai|7.4',
    'Thuppakki|2012|South Indian|Action, Thriller|A.R. Murugadoss|Vijay;Kajal Aggarwal;Vidyut Jammwal|8.1',
    'Kaththi|2014|South Indian|Action, Drama|A.R. Murugadoss|Vijay;Samantha Ruth Prabhu;Neil Nitin Mukesh|8.0',
    'Ghajini|2005|South Indian|Action, Thriller|A.R. Murugadoss|Suriya;Asin;Nayanthara|8.3',
    'Darbar|2020|South Indian|Action, Thriller|A.R. Murugadoss|Rajinikanth;Nayanthara;Nivetha Thomas|6.0',
    'Ghilli|2004|South Indian|Action, Romance|Dharani|Vijay;Trisha Krishnan;Prakash Raj|8.1',
    'Kuruvi|2008|South Indian|Action, Comedy|Dharani|Vijay;Trisha Krishnan;Suman|4.2',
    'Asuran|2019|South Indian|Action, Drama|Vetrimaaran|Dhanush;Manju Warrier;Prakash Raj|8.4',
    'Vada Chennai|2018|South Indian|Crime, Drama|Vetrimaaran|Dhanush;Ameer;Andrea Jeremiah|8.4',
    'Visaranai|2015|South Indian|Crime, Drama|Vetrimaaran|Dinesh;Samuthirakani;Kishore|8.4',
    'Viduthalai Part 1|2023|South Indian|Crime, Drama|Vetrimaaran|Soori;Vijay Sethupathi;Bhavani Sre|8.0',
    'Aadukalam|2011|South Indian|Drama|Vetrimaaran|Dhanush;Taapsee Pannu;Jayabalan|8.1',
    'Jai Bhim|2021|South Indian|Crime, Drama|T. J. Gnanavel|Suriya;Lijomol Jose;Manikandan|8.8',
    'Vettaiyan|2024|South Indian|Action, Drama|T. J. Gnanavel|Rajinikanth;Amitabh Bachchan;Fahadh Faasil|7.1',
    'Soorarai Pottru|2020|South Indian|Drama|Sudha Kongara|Suriya;Aparna Balamurali;Paresh Rawal|8.7',
    'Irudhi Suttru|2016|South Indian|Drama, Sports|Sudha Kongara|R. Madhavan;Ritika Singh;Mumtaz Sorcar|7.9',
    '96|2018|South Indian|Drama, Romance|C. Prem Kumar|Vijay Sethupathi;Trisha Krishnan;Gouri Kishan|8.5',
    'Meiyazhagan|2024|South Indian|Drama|C. Prem Kumar|Karthi;Arvind Swamy;Sri Divya|8.2',
    'Ratsasan|2018|South Indian|Crime, Thriller|Ram Kumar|Vishnu Vishal;Amala Paul;Saravanan|8.3',
    'Mundasupatti|2014|South Indian|Comedy|Ram Kumar|Vishnu Vishal;Nandita Swetha;Kaali Venkat|7.5',
    'Thani Oruvan|2015|South Indian|Action, Thriller|Mohan Raja|Jayam Ravi;Arvind Swamy;Nayanthara|8.4',
    'Velaikkaran|2017|South Indian|Action, Drama|Mohan Raja|Sivakarthikeyan;Fahadh Faasil;Nayanthara|7.3',
    'Thadam|2019|South Indian|Crime, Thriller|Magizh Thirumeni|Arun Vijay;Vidhya Pradeep;Tanya Hope|8.1',
    'Meaghamann|2014|South Indian|Action, Thriller|Magizh Thirumeni|Arya;Hansika Motwani;Sudhanshu Pandey|7.4',
    'Mankatha|2011|South Indian|Action, Thriller|Venkat Prabhu|Ajith Kumar;Arjun Sarja;Trisha Krishnan|7.7',
    'Maanaadu|2021|South Indian|Sci-Fi, Action|Venkat Prabhu|Silambarasan;S. J. Suryah;Kalyani Priyadarshan|8.3',
    'Goa|2010|South Indian|Comedy|Venkat Prabhu|Jai;Vaibhav;Premji|6.6',
    'Petta|2019|South Indian|Action, Drama|Karthik Subbaraj|Rajinikanth;Vijay Sethupathi;Nawazuddin Siddiqui|7.3',
    'Jigarthanda|2014|South Indian|Crime, Comedy|Karthik Subbaraj|Siddharth;Bobby Simha;Lakshmi Menon|8.2',
    'Jigarthanda DoubleX|2023|South Indian|Action, Drama|Karthik Subbaraj|Raghava Lawrence;S. J. Suryah;Nimisha Sajayan|8.0',
    'Pizza|2012|South Indian|Horror, Thriller|Karthik Subbaraj|Vijay Sethupathi;Remya Nambeesan;Aadukalam Naren|8.0',
    'Kabali|2016|South Indian|Action, Drama|Pa. Ranjith|Rajinikanth;Radhika Apte;Winston Chao|6.2',
    'Kaala|2018|South Indian|Action, Drama|Pa. Ranjith|Rajinikanth;Huma Qureshi;Nana Patekar|6.6',
    'Sarpatta Parambarai|2021|South Indian|Drama, Sports|Pa. Ranjith|Arya;Dushara Vijayan;Pasupathy|8.5',
    'Madras|2014|South Indian|Drama|Pa. Ranjith|Karthi;Catherine Tresa;Kalaiyarasan|7.9',
    'Enthiran|2010|South Indian|Sci-Fi, Action|S. Shankar|Rajinikanth;Aishwarya Rai Bachchan;Danny Denzongpa|7.1',
    'Sivaji: The Boss|2007|South Indian|Action, Drama|S. Shankar|Rajinikanth;Shriya Saran;Suman|7.5',
    'Anniyan|2005|South Indian|Action, Thriller|S. Shankar|Vikram;Sadha;Prakash Raj|8.2',
    'Indian|1996|South Indian|Action, Drama|S. Shankar|Kamal Haasan;Sukanya;Manisha Koirala|8.0',
    '2.0|2018|South Indian|Sci-Fi, Action|S. Shankar|Rajinikanth;Akshay Kumar;Amy Jackson|6.1',
    'Kannathil Muthamittal|2002|South Indian|Drama|Mani Ratnam|R. Madhavan;Simran;P. S. Keerthana|8.4',
    'Alaipayuthey|2000|South Indian|Drama, Romance|Mani Ratnam|R. Madhavan;Shalini;Swarnamalya|8.3',
    'Thalapathi|1991|South Indian|Crime, Drama|Mani Ratnam|Rajinikanth;Mammootty;Shobana|8.5',
    'Raavanan|2010|South Indian|Action, Adventure|Mani Ratnam|Vikram;Aishwarya Rai Bachchan;Prithviraj Sukumaran|6.8',
    'Ponniyin Selvan: I|2022|South Indian|Action, History|Mani Ratnam|Vikram;Karthi;Aishwarya Rai Bachchan|7.6',
    'Ponniyin Selvan: II|2023|South Indian|Action, History|Mani Ratnam|Vikram;Aishwarya Rai Bachchan;Jayam Ravi|7.3',
    'Drishyam|2013|South Indian|Crime, Thriller|Jeethu Joseph|Mohanlal;Meena;Asha Sarath|8.2',
    'Drishyam 2|2021|South Indian|Crime, Thriller|Jeethu Joseph|Mohanlal;Meena;Ansiba Hassan|8.4',
    'Memories|2013|South Indian|Thriller, Mystery|Jeethu Joseph|Prithviraj Sukumaran;Miya George;Meghana Raj|8.0',
    'Premam|2015|South Indian|Comedy, Romance|Alphonse Puthren|Nivin Pauly;Sai Pallavi;Madonna Sebastian|8.3',
    'Gold|2022|South Indian|Comedy, Drama|Alphonse Puthren|Prithviraj Sukumaran;Nayanthara;Ajmal Ameer|4.6',
    'Bangalore Days|2014|South Indian|Comedy, Drama|Anjali Menon|Dulquer Salmaan;Nivin Pauly;Nazriya Nazim|8.3',
    'Koode|2018|South Indian|Drama|Anjali Menon|Prithviraj Sukumaran;Nazriya Nazim;Parvathy Thiruvothu|7.6',
    'Ustad Hotel|2012|South Indian|Comedy, Drama|Anwar Rasheed|Dulquer Salmaan;Thilakan;Nithya Menen|8.2',
    'Trance|2020|South Indian|Drama, Thriller|Anwar Rasheed|Fahadh Faasil;Nazriya Nazim;Gautham Menon|7.2',
    'Aavesham|2024|South Indian|Action, Comedy|Jithu Madhavan|Fahadh Faasil;Hipzster;Mithun Jai Shankar|8.0',
    'Romancham|2023|South Indian|Comedy, Horror|Jithu Madhavan|Soubin Shahir;Arjun Ashokan;Sajin Gopu|7.5',
    'Manjummel Boys|2024|South Indian|Adventure, Thriller|Chidambaram|Soubin Shahir;Sreenath Bhasi;Balu Varghese|8.3',
    'Jan.E.Man|2021|South Indian|Comedy, Drama|Chidambaram|Basil Joseph;Lal;Arjun Ashokan|7.2',
    '2018|2023|South Indian|Drama, Thriller|Jude Anthany Joseph|Tovino Thomas;Kunchacko Boban;Asif Ali|8.3',
    'Om Shanti Oshana|2014|South Indian|Comedy, Romance|Jude Anthany Joseph|Nazriya Nazim;Nivin Pauly;Aju Varghese|7.7',
    'Minnal Murali|2021|South Indian|Action, Comedy|Basil Joseph|Tovino Thomas;Guru Somasundaram;Femina George|7.8',
    'Godha|2017|South Indian|Comedy, Drama|Basil Joseph|Tovino Thomas;Wamiqa Gabbi;Aju Varghese|7.8',
    'Kunjiramayanam|2015|South Indian|Comedy|Basil Joseph|Vineeth Sreenivasan;Dhyan Sreenivasan;Aju Varghese|7.7',
    'Kantara|2022|South Indian|Action, Thriller|Rishab Shetty|Rishab Shetty;Sapthami Gowda;Kishore|8.2',
    'Kirik Party|2016|South Indian|Comedy, Drama|Rishab Shetty|Rakshit Shetty;Rashmika Mandanna;Samyuktha Hegde|8.3',
    'Sarkari Hi. Pra. Shaale|2018|South Indian|Comedy, Drama|Rishab Shetty|Anant Nag;Ramesh Bhat;Pramod Shetty|8.0',
    'Ulidavaru Kandanthe|2014|South Indian|Crime, Drama|Rakshit Shetty|Rakshit Shetty;Kishore;Tara|8.3',
    'Avane Srimannarayana|2019|South Indian|Adventure, Comedy|Sachin Ravi|Rakshit Shetty;Shanvi Srivastava;Achyuth Kumar|7.8',
    'Sapta Sagaradaache Ello Side A|2023|South Indian|Drama, Romance|Hemanth M. Rao|Rakshit Shetty;Rukmini Vasanth;Chaithra J. Achar|8.0',
    'Sapta Sagaradaache Ello Side B|2023|South Indian|Drama, Romance|Hemanth M. Rao|Rakshit Shetty;Rukmini Vasanth;Chaithra J. Achar|7.8',
    'Lucia|2013|South Indian|Sci-Fi, Thriller|Pawan Kumar|Sathish Ninasam;Sruthi Hariharan;Achyuth Kumar|8.3',
    'U Turn|2016|South Indian|Thriller, Mystery|Pawan Kumar|Shraddha Srinath;Roger Narayan;Dileep Raj|7.8',
    'Dia|2020|South Indian|Drama, Romance|K. S. Ashoka|Pruthvi Ambaar;Kushee Ravi;Dheekshith Shetty|8.0',
    'Charlie 777|2022|South Indian|Adventure, Comedy|Kiranraj K|Rakshit Shetty;Charlie;Sangeetha Sringeri|8.8',
    'KGF: Chapter 1|2018|South Indian|Action, Crime|Prashanth Neel|Yash;Srinidhi Shetty;Ramachandra Raju|8.2',
    'KGF: Chapter 2|2022|South Indian|Action, Crime|Prashanth Neel|Yash;Sanjay Dutt;Raveena Tandon|8.2',
    'Ugramm|2014|South Indian|Action, Thriller|Prashanth Neel|Sriimurali;Haripriya;Tilak Shekar|8.0',
    'Mufti|2017|South Indian|Action, Drama|Narthan|Shiva Rajkumar;Sriimurali;Shanvi Srivastava|7.9',
    'Garuda Gamana Vrishabha Vahana|2021|South Indian|Crime, Drama|Raj B. Shetty|Raj B. Shetty;Rishab Shetty;Gopalkrishna Deshpande|8.3',
    'Ondu Motteya Kathe|2017|South Indian|Comedy, Drama|Raj B. Shetty|Raj B. Shetty;Shailashree Mulki;Usha Bhandary|8.0',
    'Bell Bottom|2019|South Indian|Comedy, Mystery|Jayatheertha|Rishab Shetty;Hariprriya;Yogaraj Bhat|8.0',
    'Joji|2021|South Indian|Crime, Drama|Dileesh Pothan|Fahadh Faasil;Baburaj;Shammi Thilakan|7.8',
    'Maheshinte Prathikaaram|2016|South Indian|Comedy, Drama|Dileesh Pothan|Fahadh Faasil;Aparna Balamurali;Soubin Shahir|8.3',
    'Thondimuthalum Driksakshiyum|2017|South Indian|Crime, Drama|Dileesh Pothan|Fahadh Faasil;Suraj Venjaramoodu;Nimisha Sajayan|8.1',
    'Kumbalangi Nights|2019|South Indian|Drama|Madhu C. Narayanan|Soubin Shahir;Shane Nigam;Sreenath Bhasi|8.5',
    'Android Kunjappan Version 5.25|2019|South Indian|Comedy, Drama|Ratheesh Balakrishnan Poduval|Soubin Shahir;Suraj Venjaramoodu;Sooraj Thelakkad|8.0',
    'Nna Thaan Case Kodu|2022|South Indian|Comedy, Drama|Ratheesh Balakrishnan Poduval|Kunchacko Boban;Gayathrie;Basil Joseph|7.7',
    'The Great Indian Kitchen|2021|South Indian|Drama|Jeo Baby|Nimisha Sajayan;Suraj Venjaramoodu;Ajitha V. M.|8.3',
    'Kaathal - The Core|2023|South Indian|Drama|Jeo Baby|Mammootty;Jyothika;R. S. Panicker|7.7',
    'Uyare|2019|South Indian|Drama|Manu Ashokan|Parvathy Thiruvothu;Asif Ali;Tovino Thomas|8.0',
    'Virus|2019|South Indian|Thriller, Drama|Aashiq Abu|Kunchacko Boban;Parvathy Thiruvothu;Asif Ali|7.9',
    'Malik|2021|South Indian|Crime, Drama|Mahesh Narayanan|Fahadh Faasil;Nimisha Sajayan;Vinay Forrt|8.0',
    'Take Off|2017|South Indian|Thriller, Drama|Mahesh Narayanan|Parvathy Thiruvothu;Kunchacko Boban;Fahadh Faasil|8.1',
    'Ayyappanum Koshiyum|2020|South Indian|Action, Thriller|Sachy|Prithviraj Sukumaran;Biju Menon;Ranjith|8.0',
    'Driving Licence|2019|South Indian|Comedy, Drama|Lal Jr.|Prithviraj Sukumaran;Suraj Venjaramoodu;Miya George|7.3',
    'Bramayugam|2024|South Indian|Horror, Thriller|Rahul Sadasivan|Mammootty;Arjun Ashokan;Sidharth Bharathan|7.8'
];
