module.exports = [
    'Aavesham|2024|South Indian|Action, Comedy|Jithu Madhavan|Fahadh Faasil;Hipzster;Mithun Jai Shankar|8.0',
    'Premalu|2024|South Indian|Comedy, Romance|Girish A. D.|Naslen;Mamitha Baiju;Sangeeth Prathap|7.8',
    'ARM|2024|South Indian|Fantasy, Adventure|Jithin Laal|Tovino Thomas;Krithi Shetty;Aishwarya Rajesh|7.2',
    'Mark Antony|2023|South Indian|Sci-Fi, Action|Adhik Ravichandran|Vishal;S. J. Suryah;Ritu Varma|7.1',
    'Lubber Pandhu|2024|South Indian|Drama, Sports|Tamizharasan Pachamuthu|Harish Kalyan;Attakathi Dinesh;Sanjana Krishnamoorthy|8.0',
    'Manjummel Boys|2024|South Indian|Adventure, Thriller|Chidambaram|Soubin Shahir;Sreenath Bhasi;Balu Varghese|8.3',
    'Aattam|2024|South Indian|Drama, Thriller|Anand Ekarshi|Vinay Forrt;Zarin Shihab;Kalabhavan Shajohn|8.2',
    'Mura|2024|South Indian|Action, Drama|Muhammed Musthafa|Suraj Venjaramoodu;Hridhu Haroon;Mala Parvathi|7.0',
    'Munjya|2024|Bollywood|Comedy, Horror|Aditya Sarpotdar|Abhay Verma;Sharvari;Mona Singh|6.7',
    'Srikanth|2024|Bollywood|Drama, Biography|Tushar Hiranandani|Rajkummar Rao;Alaya F;Jyotika|7.4',
    'Amar Singh Chamkila|2024|Bollywood|Drama, Music|Imtiaz Ali|Diljit Dosanjh;Parineeti Chopra;Apinderdeep Singh|7.8',
    'Jigra|2024|Bollywood|Action, Drama|Vasan Bala|Alia Bhatt;Vedang Raina;Manoj Pahwa|6.9',
    'Bhakshak|2024|Bollywood|Crime, Drama|Pulkit|Bhumi Pednekar;Sanjay Mishra;Sai Tamhankar|7.2',
    'Merry Christmas|2024|Bollywood|Thriller, Mystery|Sriram Raghavan|Katrina Kaif;Vijay Sethupathi;Radhika Apte|6.9',
    'Kill|2024|Bollywood|Action, Thriller|Nikhil Nagesh Bhat|Lakshya;Raghav Juyal;Tanya Maniktala|7.6',
    'Yeh Jawaani Hai Deewani|2013|Bollywood|Comedy, Romance|Ayan Mukerji|Ranbir Kapoor;Deepika Padukone;Aditya Roy Kapur|7.2',
    'Wake Up Sid|2009|Bollywood|Comedy, Drama|Ayan Mukerji|Ranbir Kapoor;Konkona Sen Sharma;Anupam Kher|7.6',
    'Brahmastra Part One: Shiva|2022|Bollywood|Fantasy, Adventure|Ayan Mukerji|Ranbir Kapoor;Alia Bhatt;Amitabh Bachchan|5.6',
    'Sita Ramam|2022|South Indian|Drama, Romance|Hanu Raghavapudi|Dulquer Salmaan;Mrunal Thakur;Rashmika Mandanna|8.5',
    'Hi Nanna|2023|Tollywood|Drama, Romance|Shouryuv|Nani;Mrunal Thakur;Kiara Khanna|8.1',
    'Lucky Baskhar|2024|Tollywood|Crime, Drama|Venky Atluri|Dulquer Salmaan;Meenakshi Chaudhary;Ayesha Khan|7.8',
    'Tillu Square|2024|Tollywood|Comedy, Crime|Mallik Ram|Siddhu Jonnalagadda;Anupama Parameswaran;Muralidhar Goud|7.1',
    'DJ Tillu|2022|Tollywood|Comedy, Crime|Vimal Krishna|Siddhu Jonnalagadda;Neha Shetty;Prince Cecil|7.2',
    'Hanu-Man|2024|Tollywood|Fantasy, Action|Prasanth Varma|Teja Sajja;Amritha Aiyer;Varalaxmi Sarathkumar|7.8',
    'Ala Vaikunthapurramuloo|2020|Tollywood|Action, Comedy|Trivikram Srinivas|Allu Arjun;Pooja Hegde;Tabu|7.3',
    'Godavari|2006|Tollywood|Drama, Romance|Sekhar Kammula|Sumanth;Kamalinee Mukherjee;Neetu Chandra|8.3',
    'Brochevarevarura|2019|Tollywood|Comedy, Crime|Vivek Athreya|Sree Vishnu;Nivetha Thomas;Nivetha Pethuraj|8.0',
    'Keedaa Cola|2023|Tollywood|Crime, Comedy|Tharun Bhascker|Chaitanya Rao;Rag Mayur;Brahmanandam|7.0',
    'The Holdovers|2023|Hollywood|Comedy, Drama|Alexander Payne|Paul Giamatti;DaVine Joy Randolph;Dominic Sessa|8.0',
    'Past Lives|2023|Hollywood|Drama, Romance|Celine Song|Greta Lee;Teo Yoo;John Magaro|7.9',
    'Perfect Days|2023|International|Drama|Wim Wenders|Koji Yakusho;Tokio Emoto;Arisa Nakano|7.9',
    'Godzilla x Kong: The New Empire|2024|Hollywood|Action, Sci-Fi|Adam Wingard|Rebecca Hall;Brian Tyree Henry;Dan Stevens|6.2',
    'Kingdom of the Planet of the Apes|2024|Hollywood|Action, Sci-Fi|Wes Ball|Owen Teague;Freya Allan;Kevin Durand|6.9',
    'The Wild Robot|2024|Hollywood|Animation, Adventure|Chris Sanders|Lupita Nyongo;Pedro Pascal;Kit Connor|8.3',
    'Flow|2024|International|Animation, Adventure|Gints Zilbalodis|No dialogue ensemble;Cat;Capybara|7.9',
    'Transformers One|2024|Hollywood|Animation, Action|Josh Cooley|Chris Hemsworth;Brian Tyree Henry;Scarlett Johansson|7.8',
    'The Boy and the Heron|2023|International|Animation, Fantasy|Hayao Miyazaki|Soma Santoki;Masaki Suda;Aimyon|7.4',
    'Suzume|2022|International|Animation, Adventure|Makoto Shinkai|Nanoka Hara;Hokuto Matsumura;Eri Fukatsu|7.6',
    'Your Name.|2016|International|Animation, Romance|Makoto Shinkai|Ryunosuke Kamiki;Mone Kamishiraishi;Masami Nagasawa|8.4',
    'A Silent Voice|2016|International|Animation, Drama|Naoko Yamada|Miyu Irino;Saori Hayami;Aoi Yuki|8.1'
];
